### PR TITLE
Add possibility to build API and WEB servers along with regular ones

### LINKED ISSUE #133: Deployment script doesn't support API server deployment
Since merging of this PR https://github.com/poanetwork/blockscout/pull/2376 Blockscout supports to launch of API server separately from web app server. Technically, API server is the Blockscout instance with the different set of ENV variables that utilizes the same DB as app instance or DB replica. Thus, API server should be launched in the same VPC.

### PR DESCRIPTION
**Pull request by ArseniiPetrovich**
Closes #133

# DETAILS
- [x] Most variables (except those related to DB) will no longer be deployed during the infrastructure deployment process as this takes time and duplicate efforts when deploying the software.
- [x] Major Ansible role refactor for better understanding and hierarchy:
  - [x] `S3`, `S3_debug` and `S3_config` were merged into single role with different tasks subsets inside.
  - [x] DRY improvements - `main_infra`, `destroy` and `attach_existing_rds` were merged into single `infrastructure` role as they depend on the same subset of tasks.
  - [x] `main_software` role were split into three roles - `build`, `deploy` and `ssm_vars` to keep each role nice and small. <details><summary>Thoughts</summary>I've decided to keep these three as a separate roles because of their low coupling and independence (tags: `build`, `deploy`, `update_vars`), but if there are any objections I can possibly merge them into single `software` role with different tasks as I made with `main_infra` role;</details>
- [x] Major refactor of the Terraform scripts;
   - [x] Create a module that will be repeatedly used to deploy API, WEB and regular servers. <details><summary>Details</summary>I've used a workaround with creating the Ansible template on top of one of the TF files which is used to call newly created module because of current Terraform limitations, that will be addressed in the near future.
API and WEB servers are served by the common loadbalancer. Due to known bug some of the API are still addressed to the WEB instance along with the write API requests.</details>
- [x] Bug fixing;
  - [x] [Major] `vpc_zone_identifier` were set along with the `availability_zones` in TF ASG resource leads to plan inconsistency;
- [x] New features
  - [x] Users can independently select a number of "regulars_servers", "web_servers" and "api_servers" they want to deploy for each chain;
- [x] Cosmetic README improvements;

# STATUS
As for now PR is in MVP (minimal viable product) stage, which means it is still not tested well, but all the functionality are in place. Also it is *NOT* backward compatible with `master` because of major changes in TF and Ansible scripts. I'll work more to see if there are any workaround to make it compatible.

# TODO
- [x] Make PR backward compatible
- [x] Test how this PR works when performing the parallel deployment
- [x] Add information about new variables to the README. 
- [x] Improve README by splitting it on self-sustaining parts.
- [x] Test attach_existing_rds script
- [x] Add possibility to create a DB with read replica
- [x] Identify the root of the issue with empty tuples while attempting to destroy TF infra.

### CODE REVIEW

**Comment by ArseniiPetrovich** [comment]
Update 1: Found a bug.
- [ ] Load balancer rules were not created properly.

**Comment by ArseniiPetrovich** [comment]
@vbaranov @symanovich-a 
Please, kindly check the pull request.

**Comment by ArseniiPetrovich** [comment]
As for now this could not be merged, at least until https://github.com/terraform-providers/terraform-provider-aws/pull/8268 is not merged.

**Comment by symanovich-a** [comment]
- [x] check infrastructure deployment
TASK [dynamodb : dynamodb_table] - during multi-chain deployment from scratch. 
 ```
error "boto.exception.JSONResponseError: JSONResponseError: 400 Bad Request\n{'__type': 'com.amazon.coral.availability#ThrottlingException', 'message': 'The rate of control plane requests made by this account is too high'}"
```
- [ ] check software deployment

**Comment by ArseniiPetrovich** [comment]
Finally, the https://github.com/terraform-providers/terraform-provider-aws/pull/8268 was merged. We can merge this PR next week.

**Comment by ArseniiPetrovich** [comment]
@vbaranov However, I can see that the documentation migrated to docs.blockscout.org. How to resolve merge conflict?

**Comment by vbaranov** [comment]
>@vbaranov However, I can see that the documentation migrated to docs.blockscout.org. How to resolve merge conflict?

@ArseniiPetrovich yes, indeed, we migrated documentation to the docs.blockscout.com. It is managed by GitBook and lives here https://github.com/blockscout/docs. In order to solve merging conflicts, I would suggest to remove updates of docs section in this PR and create a separate one to the docs repo.

**Comment by ArseniiPetrovich** [comment]
Terraform provider version released. Removing "do not merge" label.

**Pull request closed without merging**
